### ISSUE TITLE
Get this ready for public release

### ISSUE THREAD

**Issue by kj800x** [kj800x/nulinks#52]
## Things to think about
- What channels do we want to announce it via (Facebook? The Meme Collective? The Northeastern Page? The Northeastern CCIS Page? The "Not A Meme But" Page?
- Maybe reach out to SearchNEU to see their thoughts?
- Fliers (that's what SearchNEU did)?

## Todo
- [x] Make sure that the GitHub is all ready (per the Insights/Community tab)
  - [x] Contributing guidelines
  - [x] Readme #25 
- [ ] Prepare developer experience
  - [x] Ensure that the build server is back up so that we can do rapid turnaround
  - [x] Solve the Babel / Webpack issue #51 
  - [ ] Add additional tests
